core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

shop/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView, ProductView, CheckoutView

urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    path('product/<int:pk>', ProductView.as_view(), name='product'),
    path('checkout', CheckoutView.as_view(), name='checkout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse


class Products(models.Model):
    title = models.CharField(max_length=200, help_text='Introduce product title')
    price = models.FloatField()
    discount_price = models.FloatField()
    category = models.CharField(max_length=50)
    description = models.TextField(help_text='Introduce a brief description for the product')
    image = models.CharField(max_length=300)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product', args=[str(self.id)])

class Order(models.Model):
    COUNTRIES = (
        ('US', 'us'),
        ('SPAIN', 'es'),
    )

    STATES = (
        ('California', 'ca'),
        ('Barcelona', 'bcn'),
    )

    first_name = models.CharField(max_length=100)
    last_name =  models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=250)
    country = models.CharField(max_length=100, choices=COUNTRIES)
    state = models.CharField(max_length=100, choices=STATES)
    zipcode = models.CharField(max_length=100)
    items = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('order', args=[str(self.id)])
    
    

shop/forms.py
from django import forms
from .models import Order


class AddToCartForm(forms.Form):
    num_items = forms.IntegerField()

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','email','address','country','state','zipcode']
        widgets = {
            'country': forms.Select(attrs={'class': 'custom-select d-block w-100'}),
            'state': forms.Select(attrs={'class': 'custom-select d-block w-100'})
        }

shop/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from django_filters.views import FilterView

from .models import Products
from .forms import AddToCartForm, CheckoutForm
from .filters import ItemFilter


class HomeView(FilterView, ListView):
    model = Products
    template_name = 'shop/home.html'
    filterset_class = ItemFilter
    paginate_by = 8

    def get_queryset(self):
        try:
            query = self.request.GET.get('q')
        except:
            query = ''
        
        if(query != '' and query is not None):
            object_list = Products.objects.filter(title__icontains = query)
        else:
            object_list = Products.objects.all()

        return object_list
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['categories'] = list(set([product.category for product in Products.objects.all()]))

        return context


class ProductView(FormMixin, DetailView):
    model = Products
    form_class = AddToCartForm
    template_name = 'shop/product.html'
    context_object_name = 'product'
    success_url = reverse_lazy('home')
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        cart_items = self.request.session.get('cart', {})

        if(str(self.object.id) in cart_items):
            cart_items[str(self.object.id)] += form.cleaned_data['num_items']
        else:
            cart_items[str(self.object.id)] = form.cleaned_data['num_items']

        self.request.session['cart'] = cart_items

        return super().form_valid(form)


class CheckoutView(FormMixin, ListView):
    model = Products
    template_name = 'shop/checkout.html'
    form_class = CheckoutForm
    success_url = reverse_lazy('home')

    def get_queryset(self):
        cart_items = self.request.session.get('cart', {})
        
        return Products.objects.filter(id__in = cart_items)
    
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        cart_items = self.request.session.get('cart', {})
        total = 0

        for product in data['object_list']:
            if (str(product.id)) in cart_items:
                total += product.discount_price * cart_items[str(product.id)]

        data['total'] = total

        return data
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object_list = self.get_queryset()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        order = form.save(commit=False)
        order.items = self.request.session.get('cart', {})
        order.save()

        self.request.session.flush()

        return super().form_valid(form)

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>My Django E-commerce</title>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="{% static 'shop/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="{% static 'shop/css/mdb.min.css' %}" rel="stylesheet">
        <!-- Your custom styles (optional) -->
        <link href="{% static 'shop/css/style.min.css' %}" rel="stylesheet">
        {% block extra_style %}
        {% endblock extra_style %}
        
    </head>
    <body>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">
                
                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="{% url 'home' %}">
                    <strong class="blue-text">DJECOMM</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link waves-effect" href="{% url 'home' %}">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="#" target="_blank">Link1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="#" target="_blank">Link2</a>
                        </li>
                    </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'checkout' %}">
                                {% if request.session.cart %}
                                    <span class="badge red z-depth-1 mr-1"> {{ request.session.cart|length }} </span>
                                {% endif %}
                                <i class="fas fa-shopping-cart"></i>
                                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        <!-- Navbar -->

        {% block content %}
        {% endblock content %}
        
        <!--Footer-->
        <footer class="page-footer text-center font-small mt-4 wow fadeIn">

            <!-- Social icons -->
            <div class="pb-4">
                <a href="#" target="_blank">
                    <i class="fab fa-facebook-f mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-twitter mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-youtube mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-google-plus-g mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-dribbble mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-pinterest mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-github mr-3"></i>
                </a>

                <a href="#" target="_blank">
                    <i class="fab fa-codepen mr-3"></i>
                </a>
            </div>
            <!-- Social icons -->

            <!--Copyright-->
            <div class="footer-copyright py-3">
                © 2019 Copyright:
                <a href="#" target="_blank"> DJECOMM </a>
            </div>
            <!--/.Copyright-->

        </footer>
        <!--/.Footer-->

        <!-- SCRIPTS -->
        <!-- JQuery -->
        <script type="text/javascript" src="{% static 'shop/js/jquery-3.4.1.min.js' %}"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="{% static 'shop/js/popper.min.js' %}"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="{% static 'shop/js/bootstrap.min.js' %}"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="{% static 'shop/js/mdb.min.js' %}"></script>
        <!-- Initializations -->
        <script type="text/javascript">
            // Animations initialization
            new WOW().init();
        </script>        

    </body>
</html>

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}


{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'checkout' %}" method="POST">
              {% csrf_token %}

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--firstName-->
                  <div class="md-form ">
                    {{ form.first_name.errors }}
                    {{ form.first_name.label_tag }}
                    <input type="text" class="form-control" id="{{ form.first_name.id_for_label }}" maxlength="{{ form.first_name.field.max_length }}" name="{{ form.first_name.html_name }}" /> 
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    {{ form.last_name.errors }}
                    {{ form.last_name.label_tag }}
                    <input type="text" class="form-control" id="{{ form.last_name.id_for_label }}" maxlength="{{ form.last_name.field.max_length }}" name="{{ form.last_name.html_name }}" /> 
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--email-->
              <div class="md-form mb-5">
                {{ form.email.errors }}
                {{ form.email.label_tag }}
                <input type="text" class="form-control" id="{{ form.email.id_for_label }}" maxlength="{{ form.email.field.max_length }}" name="{{ form.email.html_name }}" placeholder="youremail@example.com" /> 
              </div>

              <!--address-->
              <div class="md-form mb-5">
                {{ form.address.errors }}
                {{ form.address.label_tag }}
                <input type="text" class="form-control" id="{{ form.address.id_for_label }}" maxlength="{{ form.address.field.max_length }}" name="{{ form.address.html_name }}" placeholder="1234 Main St" /> 
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  {{ form.country.errors }}
                  {{ form.country.label_tag }}
                  {{ form.country }}
                  
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">
                  {{ form.state.errors }}
                  {{ form.state.label_tag }}
                  {{ form.state }}

                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">
                  {{ form.zipcode.errors }}
                  {{ form.zipcode.label_tag }}
                  <input type="text" class="form-control" id="{{ form.zipcode.id_for_label }}" maxlength="{{ form.zipcode.field.max_length }}" name="{{ form.zipcode.html_name }}" placeholder="1234" /> 

                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            {% if request.session.cart %}
              <span class="badge badge-secondary badge-pill">{{ request.session.cart|length }}</span>
            {% endif %}
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% load shop_extras %}
            {% for product in products_list %}
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">{{ product.title }}</h6>               
                  <small class="text-muted">{{ product.description }}</small>
                </div>
                <span class="text-muted">
                  <small>{{ request.session.cart|get:product.id }}</small> x {{ product.discount_price|floatformat:2 }} €
                </span>
              </li>
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (€)</span>
              <strong>{{ total|floatformat:2 }} €</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}

shop/templates/shop/home.html
{% extends 'shop/base.html' %}

{% block extra_style %}
<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>
{% endblock extra_style %}

{% block content %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>DJEcomm site</strong>
              </h1>

              <p>
                <strong>Best e-commerce site made in Django</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>DJEcomm site</strong>
              </h1>

              <p>
                <strong>Best e-commerce site made in Django</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>DJEcomm site</strong>
              </h1>

              <p>
                <strong>Best e-commerce site made in Django</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.get_full_path == '/' %} active {% endif %}">
              <a class="nav-link" href="{% url 'home' %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% for category in categories %}
              <li class="nav-item {% if category in request.get_full_path %} active {% endif %}">
                <a class="nav-link" href="{% url 'home' %}?category={{ category }}">{{ category }}</a>
              </li>
            {% endfor %}

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q">
            </div>
          </form> 
          
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        {% for product in products_list %}
          {% if forloop.first or forloop.counter0|divisibleby:"4" %}
            <!--Grid row-->
            <div class="row wow fadeIn">
          {% endif %}
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4">
        
                <!--Card-->
                <div class="card">

                  <!--Card image-->
                  <div class="view overlay">
                    <img src="{{ product.image }}" class="card-img-top" alt="">
                    <a href="{{ product.get_absolute_url }}">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                  <!--Card image-->
                
                  <!--Card content-->
                
                  <div class="card-body text-center">
                    <!--Category & Title-->
                    <a href="{{ product.get_absolute_url }}" class="grey-text">
                      <h5>{{ product.category }}</h5>
                    </a>
                    <h5>
                      <strong>
                        <a href="{{ product.get_absolute_url }}" class="dark-grey-text">{{ product.title }}
                          <span class="badge badge-pill danger-color">NEW</span>
                        </a>
                      </strong>
                    </h5>
                    <h4 class="font-weight-bold blue-text">
                      <strong>{{ product.price|floatformat:2 }} €</strong>
                    </h4>
                  </div>
                  <!--Card content-->

                </div>
                <!--Card-->

              </div>
              <!--Grid column-->
            
          {% if forloop.last or forloop.counter|divisibleby:"4" %}
            </div>
            <!--Grid row-->
          {% endif %}

          {% empty %}
            <p>Sorry, no items availables now </p>

        {% endfor %}

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          
        {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
          {% if i == page_obj.number %}
            <li class="page-item active">
              <a class="page-link" href="{{ request.path }}?page={{ i }}">{{ i }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{{ request.path }}?page={{ i }}">{{ i }} 
              </a>
            </li>
          {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
          <!--Arrow right-->
          <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        {% endif %}

        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

shop/templates/shop/product.html
{% extends 'shop/base.html' %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ product.image }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ product.category }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-1">
                <del>{{ product.price|floatformat:2 }} €</del>
              </span>
              <span>{{ product.discount_price|floatformat:2 }} €</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ product.description }}</p>

            <form class="d-flex justify-content-left" action="" method="POST">
              {% csrf_token %}
              <!-- Default input -->
              <input type="number" value="1" aria-label="Cart" class="form-control" style="width: 100px" name="{{ form.num_items.html_name }}" required_id="{{ form.num_items.id_for_label }}">
              <button class="btn btn-primary btn-md my-0 p" type="submit" id="{{ product.id }}">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
            </form> 

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}

  